# syntax=docker/dockerfile:1
FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN --mount=type=cache,target=/root/.npm \
    npm ci

COPY . .

ARG VITE_API_BASE=http://103.7.41.145:3000/api
ARG VITE_CLOUDINARY_CLOUD_NAME=diuwaesix
ARG VITE_CLOUDINARY_UPLOAD_PRESET=happmall
ENV VITE_API_BASE=$VITE_API_BASE
ENV VITE_CLOUDINARY_CLOUD_NAME=$VITE_CLOUDINARY_CLOUD_NAME
ENV VITE_CLOUDINARY_UPLOAD_PRESET=$VITE_CLOUDINARY_UPLOAD_PRESET

RUN npm run build


FROM node:22-slim AS runner

RUN --mount=type=cache,target=/root/.npm \
    npm install -g wrangler

COPY --from=builder /app/dist ./dist

EXPOSE 4000

# dist/server/wrangler.json is generated by @cloudflare/vite-plugin at build time
# and already contains the correct main/assets config — use it directly
WORKDIR /app/dist/server
CMD ["wrangler", "dev", "--config", "wrangler.json", "--port", "4000", "--ip", "0.0.0.0"]
