/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed.index'
import { Route as AuthedWheelRouteImport } from './routes/_authed.wheel'
import { Route as AuthedVouchersRouteImport } from './routes/_authed.vouchers'
import { Route as AuthedUsersRouteImport } from './routes/_authed.users'
import { Route as AuthedUserSettingsRouteImport } from './routes/_authed.user-settings'
import { Route as AuthedStockMovementsRouteImport } from './routes/_authed.stock-movements'
import { Route as AuthedReviewsRouteImport } from './routes/_authed.reviews'
import { Route as AuthedProductsRouteImport } from './routes/_authed.products'
import { Route as AuthedPosOrdersRouteImport } from './routes/_authed.pos-orders'
import { Route as AuthedOrdersRouteImport } from './routes/_authed.orders'
import { Route as AuthedNewsRouteImport } from './routes/_authed.news'
import { Route as AuthedInventoryRouteImport } from './routes/_authed.inventory'
import { Route as AuthedCategoriesRouteImport } from './routes/_authed.categories'
import { Route as AuthedAccountsRouteImport } from './routes/_authed.accounts'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWheelRoute = AuthedWheelRouteImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedVouchersRoute = AuthedVouchersRouteImport.update({
  id: '/vouchers',
  path: '/vouchers',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUsersRoute = AuthedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUserSettingsRoute = AuthedUserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStockMovementsRoute = AuthedStockMovementsRouteImport.update({
  id: '/stock-movements',
  path: '/stock-movements',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedReviewsRoute = AuthedReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedProductsRoute = AuthedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPosOrdersRoute = AuthedPosOrdersRouteImport.update({
  id: '/pos-orders',
  path: '/pos-orders',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOrdersRoute = AuthedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedNewsRoute = AuthedNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoryRoute = AuthedInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCategoriesRoute = AuthedCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAccountsRoute = AuthedAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/accounts': typeof AuthedAccountsRoute
  '/categories': typeof AuthedCategoriesRoute
  '/inventory': typeof AuthedInventoryRoute
  '/news': typeof AuthedNewsRoute
  '/orders': typeof AuthedOrdersRoute
  '/pos-orders': typeof AuthedPosOrdersRoute
  '/products': typeof AuthedProductsRoute
  '/reviews': typeof AuthedReviewsRoute
  '/stock-movements': typeof AuthedStockMovementsRoute
  '/user-settings': typeof AuthedUserSettingsRoute
  '/users': typeof AuthedUsersRoute
  '/vouchers': typeof AuthedVouchersRoute
  '/wheel': typeof AuthedWheelRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/accounts': typeof AuthedAccountsRoute
  '/categories': typeof AuthedCategoriesRoute
  '/inventory': typeof AuthedInventoryRoute
  '/news': typeof AuthedNewsRoute
  '/orders': typeof AuthedOrdersRoute
  '/pos-orders': typeof AuthedPosOrdersRoute
  '/products': typeof AuthedProductsRoute
  '/reviews': typeof AuthedReviewsRoute
  '/stock-movements': typeof AuthedStockMovementsRoute
  '/user-settings': typeof AuthedUserSettingsRoute
  '/users': typeof AuthedUsersRoute
  '/vouchers': typeof AuthedVouchersRoute
  '/wheel': typeof AuthedWheelRoute
  '/': typeof AuthedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/accounts': typeof AuthedAccountsRoute
  '/_authed/categories': typeof AuthedCategoriesRoute
  '/_authed/inventory': typeof AuthedInventoryRoute
  '/_authed/news': typeof AuthedNewsRoute
  '/_authed/orders': typeof AuthedOrdersRoute
  '/_authed/pos-orders': typeof AuthedPosOrdersRoute
  '/_authed/products': typeof AuthedProductsRoute
  '/_authed/reviews': typeof AuthedReviewsRoute
  '/_authed/stock-movements': typeof AuthedStockMovementsRoute
  '/_authed/user-settings': typeof AuthedUserSettingsRoute
  '/_authed/users': typeof AuthedUsersRoute
  '/_authed/vouchers': typeof AuthedVouchersRoute
  '/_authed/wheel': typeof AuthedWheelRoute
  '/_authed/': typeof AuthedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/accounts'
    | '/categories'
    | '/inventory'
    | '/news'
    | '/orders'
    | '/pos-orders'
    | '/products'
    | '/reviews'
    | '/stock-movements'
    | '/user-settings'
    | '/users'
    | '/vouchers'
    | '/wheel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/accounts'
    | '/categories'
    | '/inventory'
    | '/news'
    | '/orders'
    | '/pos-orders'
    | '/products'
    | '/reviews'
    | '/stock-movements'
    | '/user-settings'
    | '/users'
    | '/vouchers'
    | '/wheel'
    | '/'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/accounts'
    | '/_authed/categories'
    | '/_authed/inventory'
    | '/_authed/news'
    | '/_authed/orders'
    | '/_authed/pos-orders'
    | '/_authed/products'
    | '/_authed/reviews'
    | '/_authed/stock-movements'
    | '/_authed/user-settings'
    | '/_authed/users'
    | '/_authed/vouchers'
    | '/_authed/wheel'
    | '/_authed/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/wheel': {
      id: '/_authed/wheel'
      path: '/wheel'
      fullPath: '/wheel'
      preLoaderRoute: typeof AuthedWheelRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/vouchers': {
      id: '/_authed/vouchers'
      path: '/vouchers'
      fullPath: '/vouchers'
      preLoaderRoute: typeof AuthedVouchersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/users': {
      id: '/_authed/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthedUsersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/user-settings': {
      id: '/_authed/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof AuthedUserSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/stock-movements': {
      id: '/_authed/stock-movements'
      path: '/stock-movements'
      fullPath: '/stock-movements'
      preLoaderRoute: typeof AuthedStockMovementsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/reviews': {
      id: '/_authed/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthedReviewsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/products': {
      id: '/_authed/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthedProductsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/pos-orders': {
      id: '/_authed/pos-orders'
      path: '/pos-orders'
      fullPath: '/pos-orders'
      preLoaderRoute: typeof AuthedPosOrdersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/orders': {
      id: '/_authed/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthedOrdersRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/news': {
      id: '/_authed/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof AuthedNewsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventory': {
      id: '/_authed/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof AuthedInventoryRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/categories': {
      id: '/_authed/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AuthedCategoriesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/accounts': {
      id: '/_authed/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthedAccountsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedAccountsRoute: typeof AuthedAccountsRoute
  AuthedCategoriesRoute: typeof AuthedCategoriesRoute
  AuthedInventoryRoute: typeof AuthedInventoryRoute
  AuthedNewsRoute: typeof AuthedNewsRoute
  AuthedOrdersRoute: typeof AuthedOrdersRoute
  AuthedPosOrdersRoute: typeof AuthedPosOrdersRoute
  AuthedProductsRoute: typeof AuthedProductsRoute
  AuthedReviewsRoute: typeof AuthedReviewsRoute
  AuthedStockMovementsRoute: typeof AuthedStockMovementsRoute
  AuthedUserSettingsRoute: typeof AuthedUserSettingsRoute
  AuthedUsersRoute: typeof AuthedUsersRoute
  AuthedVouchersRoute: typeof AuthedVouchersRoute
  AuthedWheelRoute: typeof AuthedWheelRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAccountsRoute: AuthedAccountsRoute,
  AuthedCategoriesRoute: AuthedCategoriesRoute,
  AuthedInventoryRoute: AuthedInventoryRoute,
  AuthedNewsRoute: AuthedNewsRoute,
  AuthedOrdersRoute: AuthedOrdersRoute,
  AuthedPosOrdersRoute: AuthedPosOrdersRoute,
  AuthedProductsRoute: AuthedProductsRoute,
  AuthedReviewsRoute: AuthedReviewsRoute,
  AuthedStockMovementsRoute: AuthedStockMovementsRoute,
  AuthedUserSettingsRoute: AuthedUserSettingsRoute,
  AuthedUsersRoute: AuthedUsersRoute,
  AuthedVouchersRoute: AuthedVouchersRoute,
  AuthedWheelRoute: AuthedWheelRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
